swagger: '2.0'
info:
  title: Todo list API
  description: ''
  contact: {}
  license: {}
  version: 1.0.0
host: ''
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
